# Generated by Django 5.0 on 2023-12-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_test_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_new_field',
        ),
    ]
