# Generated by Django 5.0 on 2024-01-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_flappybirdstudyresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='flappybirdstudyresult',
            name='s1_color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='flappybirdstudyresult',
            name='s1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flappybirdstudyresult',
            name='s2_opinion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
