# Generated by Django 5.0 on 2024-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_flappybirdstudyresult_s1_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flappybirdstudyresult',
            name='s3_preference',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
