# Generated by Django 5.0 on 2024-01-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0004_flappybirdstudyresult_s3_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='flappybirdstudyresult',
            name='prolific_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
