# Generated by Django 5.0 on 2024-01-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_score', models.FloatField(blank=True, null=True)),
                ('game_time', models.FloatField(blank=True, null=True)),
                ('s1_q1', models.CharField(blank=True, max_length=10, null=True)),
                ('s1_q2', models.IntegerField(blank=True, null=True)),
                ('s2_q1', models.IntegerField(blank=True, null=True)),
                ('survey_name', models.CharField(blank=True, max_length=25, null=True)),
                ('survey_color', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
