version: '3.9'
# Defining the compose version
services:

 # Nginx server
 nginx:
 
   # Build context
   build: ./nginx
   
   # Mapping machine and container ports
   ports:
     - 80:80
     - 443:443
     
   # Storage volumes
   volumes:
     - static_volume:/var/www/static/:/var/www/static
   depends_on:
     - web
   restart: "on-failure"

#  # To handle HTTPS connection certification
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw


 # Django application
 web:
 
   # Build context
   build: ./src
   
   # Build commands
   command: sh -c "python manage.py makemigrations --noinput &&
                   python manage.py migrate --noinput &&
                   python manage.py collectstatic --clear --noinput &&
                   gunicorn --config gunicorn_config.py cairo_project.wsgi:application"
                   
   # Storage volumes
   volumes:
     - static_volume:/var/www/static/:/var/www/static
     
   # Exposing port 8000
   expose: 
   - 8000
   restart: "on-failure"
volumes:
 postgres_data:
 static_volume:
 media_volume: