version: '3.9'
# Defining the compose version
services:

 # Nginx server
 nginx:
 
   # Build context
   build: ./nginx
   
   # Mapping machine and container ports
   ports:
     - 1337:80
     
   # Storage volumes
   volumes:
     - static_volume:/home/app/web/staticfiles
     - media_volume:/home/app/web/mediafiles
   depends_on:
     - web
   restart: "on-failure"
   
 # Django application
 web:
 
   # Build context
   build: ./src
   
   # Build commands
   command: sh -c "python manage.py makemigrations --noinput &&
                   python manage.py migrate --noinput &&
                   
                   gunicorn cairo_project.wsgi:application --bind 0.0.0.0:8000"
                   
   # Storage volumes
   volumes:
     - static_volume:/home/app/web/staticfiles
     - media_volume:/home/app/web/mediafiles
     
   # Exposing port 8000
   expose: 
   - 8000
   restart: "on-failure"
volumes:
 postgres_data:
 static_volume:
 media_volume: