# Generated by Django 5.0 on 2023-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('game_score', models.FloatField()),
                ('game_time', models.FloatField()),
                ('s1_q1', models.CharField(max_length=10)),
                ('s1_q2', models.IntegerField()),
                ('s2_q1', models.IntegerField()),
            ],
        ),
    ]
