# Generated by Django 5.0 on 2023-12-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_new_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
